fix(grid): check that `this.grid_rows_by_docname` isn't undefined
Sentry FRAPPE-60X

```
TypeError: this.grid_rows_by_docname is undefined
  at Grid.set_value(../../../../../apps/frappe/frappe/public/js/frappe/form/grid.js:793:41)
  at fn(../../../../../apps/frappe/frappe/public/js/frappe/form/form.js:317:40)
  at o/<(../../../../../apps/frappe/frappe/public/js/frappe/model/model.js:604:27)
```

Signed-off-by: Akhil Narang <me@akhilnarang.dev>
(cherry picked from commit 3b5059b7bf3adb7d4984d0b7c911574d25f552bb)