fix: outgoing email account handlng (backport #24656) (#24685)
* fix: Bail if no SMTP acccount can be found

Currently we give this weird error instead of just saying no outgoing email account is configured.

```
AttributeError: 'NoneType' object has no attribute 'get_smtp_server'
  File "frappe/email/queue.py", line 154, in flush
    email_queue.send()
  File "frappe/email/doctype/email_queue/email_queue.py", line 160, in send
    with SendMailContext(self, smtp_server_instance) as ctx:
  File "frappe/email/doctype/email_queue/email_queue.py", line 236, in __init__
    self.smtp_server: SMTPServer = smtp_server_instance or self.email_account_doc.get_smtp_server()
```

(cherry picked from commit 89a7badd5d4cb588a964b991db019d6ec5e50d45)

* fix: Fetch SMTP server inside context

Currently if smtp server creation fails email queue is endlessly
retried. It should just fail if there's no outgoing account.

(cherry picked from commit 12b37ba3edb572039fcbf99d1d038dc1842787f2)

# Conflicts:
#	frappe/email/doctype/email_queue/email_queue.py

* chore: conflicts

---------

Co-authored-by: Ankush Menat <ankush@frappe.io>