fix(query_report): sentry FRAPPE-6P0
TypeError: Cannot read properties of undefined (reading 'ref_doctype')
  at <anonymous>(../../../../../apps/frappe/frappe/public/js/frappe/views/reports/query_report.js:417:58)

Signed-off-by: Akhil Narang <me@akhilnarang.dev>
(cherry picked from commit 43ebaddbb1acc480cdb5b4310656d278fc0b38ba)