fix(rq): randomize worker name with uuid (#9614)
fixes issue with rq where worker with the same name already exists.
cases where a pid gets killed and is respawned with the same pid, when
the worker isn't dead and a new worker is being spawned; causes the
following error:

ValueError: There exists an active worker named u'xxxxxxxxxxxx.y' already

fixed by appending random hex uuid for every worker.

inspo: https://github.com/rq/rq/blob/master/rq/worker.py#L187

Signed-off-by: Chinmay D. Pai <chinmaydpai@gmail.com>