fix(table_multiselect): sentry FRAPPE-6QQ
```
TypeError: Cannot read properties of undefined (reading 'fields')
  at frappe.ui.form.ControlTableMultiSelectget_link_field(../../../../../apps/frappe/frappe/public/js/frappe/form/controls/table_multiselect.js:151:28)
  at frappe.ui.form.ControlTableMultiSelectset_formatted_input(../../../../../apps/frappe/frappe/public/js/frappe/form/controls/table_multiselect.js:124:27)
  at _a.set_input(../../../../../apps/frappe/frappe/public/js/frappe/form/controls/data.js:247:8)
  at update_input(../../../../../apps/frappe/frappe/public/js/frappe/form/controls/base_input.js:89:8)
  at _a.refresh_input(../../../../../apps/frappe/frappe/public/js/frappe/form/controls/base_input.js:110:5)
  at frappe.ui.form.Controlrefresh(../../../../../apps/frappe/frappe/public/js/frappe/form/controls/base_control.js:140:9)
  at frappe.ui.form.Layoutattach_doc_and_docfields(../../../../../apps/frappe/frappe/public/js/frappe/form/layout.js:490:59)
  at frappe.ui.form.Layoutrefresh(../../../../../apps/frappe/frappe/public/js/frappe/form/layout.js:344:8)
  at frappe.ui.form.Formrefresh_fields(../../../../../apps/frappe/frappe/public/js/frappe/form/form.js:679:15)
  at <anonymous>(../../../../../apps/frappe/frappe/public/js/frappe/form/form.js:618:16)```

Signed-off-by: Akhil Narang <me@akhilnarang.dev>
(cherry picked from commit 3b2c2c586a3c65d11dbed0634f00e50035536164)