fix: 'TopBarItem' object does not support item assignment #17926 (#17927)
TypeError: 'TopBarItem' object does not support item assignment
(cherry picked from commit 2b90397427087045974918fa5a3ee76f84cae38b)

Co-authored-by: Faris Ansari <netchampfaris@users.noreply.github.com>